### ISSUE TITLE
Add a power-up Creator/Maker

### ISSUE THREAD

**Issue by AlexisBeaulieu2000** [MammaMiaTeam/NSMB-Editor#16]
Add a power-up Creator/Maker for made a power-up custom with a Lots of choices, functionnality Already usable and custom presset for made a power-up

exemple: in the functionnality of power-up you can add all functionnality of the feather of New SUPER MARIO BROS. 2 with the Flying functionnality.

**Comment by TheGameratorT** [comment]
No, that would be extremely limited and uncreative as you would only be mixing multiple powerups in that "creator". Also making new powerups requires modifying the game code and graphics tables as well.
